name: Build

on: [push]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install mingw-w64
        run: sudo apt-get install -y mingw-w64
        
      - name: Install windows build
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Run tests
        run: cargo test --verbose

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Archive Linux
        run: tar -czf padoutput-linux.tar.gz target/x86_64-unknown-linux-gnu/release/padoutput

      - name: Archive Windows
        run: 7z a padoutput-windows.zip target/x86_64-pc-windows-gnu/release/padoutput.exe
